channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.1.3
  - r-essentials
  - r-formatR
  - r-sessioninfo
  - r-remotes
  - r-biocmanager
  - bioconductor-BiocVersion=3.14
  - r-ggplot2
  - r-patchwork
  - r-Seurat
  - r-DT
  - r-tidyverse
  - r-pheatmap
  - r-ashr
  - r-ggrepel
  - r-upsetr
  - r-knitr
  - r-rmarkdown
  - r-markdown
  - r-bookdown
  - r-openxlsx
  - r-readr
  - r-magrittr
  - r-dplyr
  - r-RColorBrewer
  - r-future
  - r-reticulate
  - r-uwot
  - r-future.apply
  - r-metap
  - r-enrichR
  - r-shiny
  - r-qqconf
  - r-SparseM
  - r-MatrixModels
  - r-mnormt
  - r-TH.data
  - r-sandwich
  - r-plotrix
  - r-mathjaxr
  - r-diagram
  - r-curl
  - r-openssl
  - r-RcppParallel
  - r-RcppTOML
  - r-quantreg
  - r-multcomp
  - r-prodlim
  - r-sn
  - r-mutoss
  - r-TFisher
  - r-metap
  - bioconductor-SingleCellExperiment
  - bioconductor-multtest
  - bioconductor-limma
  - bioconductor-deseq2
  - bioconductor-ensdb.hsapiens.v75
  - bioconductor-BiocFileCache
  - bioconductor-biomaRt
  - bioconductor-GenomicFeatures
  - bioconductor-ensembldb
