channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.1.3
  - r-essentials
  - r-remotes
  - r-biocmanager
  - r-formatR
  - r-sessioninfo
  - r-DT
  - bioconductor-deseq2
  - bioconductor-ensdb.hsapiens.v75
  - r-tidyverse
  - r-pheatmap
  - r-ashr
  - r-ggrepel
  - r-upsetr
  - r-knitr
  - r-rmarkdown
  - r-markdown
  - r-bookdown
  - r-openxlsx
  - r-readr
  - r-magrittr
  - r-dplyr
  - r-RColorBrewer
  - r-ggplot2
  - r-patchwork
  - r-Seurat
  - r-future
  - r-reticulate
  - r-uwot
  - r-future.apply
  - r-metap
  - r-enrichR
  - r-shiny
  - bioconductor-SingleCellExperiment
  - r-qqconf
