name: deploy
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
defaults:
  run:
    shell: bash -l {0}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MicromambaCreateEnv
        uses: mamba-org/setup-micromamba@main
        with:
          environment-name: Rseurat
          environment-file: configs/conda.yml
          #cache-env: true
      - name: MicromambaActivateEnv
        run: micromamba activate Rseurat
      - name: TidyverseDependencies
        run: |
          sudo apt update && sudo apt install -y libicu-dev make libcurl4-openssl-dev libssl-dev zlib1g-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjpeg-dev libpng-dev libtiff-dev pandoc libxml2-dev
      - name: InstallSeuratDatasets
        run: |
          Rscript -e "install.packages(pkgs='ifnb.SeuratData', repos='https://seurat.nygenome.org/', type='source')"
          Rscript -e "install.packages(pkgs='pbmc3k.SeuratData', repos='https://seurat.nygenome.org/', type='source')"
      - name: DownloadZenodo
        working-directory: ./rmd
        run: |
          Rscript -e "utils::download.file('https://zenodo.org/record/7891484/files/panc_sub_processed.RDS?download=1',destfile='datasets/preprocessed_rds/panc_sub_processed.RDS',method='wget')"
      - name: RmarkdownRenderSite
        run: Rscript -e "rmarkdown::render_site('rmd')"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./rmd/site
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
