name: deploy
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash -l {0}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
# TODO: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MicromambaCreateEnv
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: Rseurat
          environment-file: configs/conda.yml
          cache-env: true
      - name: MicromambaActivateEnv
        run: micromamba activate Rseurat
      - name: RemoteInstallGH
        run: |
          Rscript -e "remotes::install_github('theislab/kBET')"
          Rscript -e "remotes::install_github('satijalab/seurat-data')"
          Rscript -e "SeuratData::InstallData('ifnb')"
          Rscript -e "SeuratData::InstallData('pbmc3k')"
      - name: RmarkdownRenderSite
        run: Rscript -e "rmarkdown::render_site('rmd')"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./rmd/site
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
